import bundler from "../../bundler/index.mjs"
import path from "node:path"

import {
	getExportedLibraryFunctions,
	determineFunctionsToAutoGenerate,
	autoGenerateFunctions,
	deleteObsoleteAutoGeneratedFunctions,
	autoGenerateModuleIndex,
} from "@anio-jsbundler/core"

export default async function(project) {
	const library_functions = await getExportedLibraryFunctions(project)

	const autogenerate = await determineFunctionsToAutoGenerate(
		project,
		library_functions
	)

	// after this step, we can be sure that all functions and associated factories
	// exist on disk whether that be in /src/export or /src/auto
	await autoGenerateFunctions(project, autogenerate)

	// do some housekeeping and delete obsolete (no longer needed)
	// auto-generated functions
	await deleteObsoleteAutoGeneratedFunctions(project, autogenerate)

	// generate the module's index as a last step
	await autoGenerateModuleIndex(project, library_functions)

	/*
	await bundler(
		project, {
			entry: path.resolve(project.root, "src", "auto", "_index.mjs"),
			output: path.resolve(project.root, "build", "lib.mjs")
		}
	)*/
}
